name: macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest
