name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  build-gcc:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-24.04
      c_compiler: gcc-14
      cxx_compiler: g++-14

  build-clang:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-24.04
      c_compiler: clang-16
      cxx_compiler: clang++-16
